# Generated by Django 3.1.2 on 2020-12-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target_finder_input',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='target_finder_input',
            name='last_name',
        ),
        migrations.AddField(
            model_name='target_finder_input',
            name='alliances',
            field=models.BooleanField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
