@startuml
class NameForm(forms.Form):


class Proritize_Indicato(forms.ModelForm):


    class Meta:


class DateInput(forms.DateInput):



class DateForm(forms.Form):


class MyModelForm(forms.ModelForm):
    class Meta:

@enduml